### ISSUE TITLE
Badger.ExperimentMonitor: Disable the global progress bar when the experiment is finished

### ISSUE THREAD

**Issue by borjafdezgauna** [borjafdezgauna/RLSimion#101]

**Comment by alegd** [comment]
I see no description here. Can you give some detail? Like what do you mean by disable: to disappear the bar like when a single experiment is finished and the local progress bar disappear or instead put it in gray color indicating there would be no more progress or something like that.

**Comment by borjafdezgauna** [comment]
ProgressBars (and nearly all the rest of gui objects) have a property called IsEnabled. That is the property you have to bind with a boolean property of the class. An example from ReportsWindowView.xaml:
` <Button  HorizontalAlignment="Right" BorderBrush="SlateGray" Margin="10,0" Height="30"
                                     cal:Message.Attach="[Event Click]=[Action saveReports()]"
                                    IsEnabled="{Binding Path=**bCanSaveReports**}">
                    <StackPanel Orientation="Horizontal">
                        <TextBlock VerticalAlignment="Center" Margin="3,0,0,0">Save all</TextBlock>
                        <Image Width="25" Height="25" Source="{StaticResource save-all}"  Margin="3,0,3,0"/>
                    </StackPanel>
</Button>`

And, in the viewmodel class ReportsWindowViewModel:
` private bool m_bCanGenerateReports = false;
        public bool bCanGenerateReports { get { return m_bCanGenerateReports; }
set { m_bCanGenerateReports = value; NotifyOfPropertyChange(() => bCanGenerateReports); } }`

**Comment by alegd** [comment]
Ok, I'm aware that property exists but I was thinking about the goal of this issue, because when developers enable/disable a component we do that in order to permit/avoid users interaction with that component like a button, checkbox, etc. once some rule has been fulfilled, but the thing is users never interact with a progress bar because this is more like an informative component. In fact you can test it yourself and manually set IsEnabled to False in a ProgressBar and check  that nothing happens, not even color changes.

**Comment by borjafdezgauna** [comment]
Ok, I see... point made! 👍 

maybe hide it when the experiment finishes? I find it a bit weird that it stays full-colored after finishing, maybe it's only me :)
