### ISSUE TITLE
Use GPU version of CNTK

### ISSUE THREAD

**Issue by zimmerrol** [borjafdezgauna/RLSimion#127]
I have just noticed that since CNTK version 2.4 (released on 2018-01-31) the code can be compiled using Visual Studio 2017 using CUDA 9 and cuDNN 7. Maybe one can add the possibility to use not only the CPU version of CNTK but also the GPU-powered version. Or is this already implemented?

Furthermore, it might be interesting to take a look at the latest version (2.5) as they have added support for _Distributed Training with Mulitple Learners_. They would allow the user to not only use differerent agents to run "copies" of the same experiment but also to use a crowd of agents to run just one, computationally costly experiment.

**Comment by borjafdezgauna** [comment]
I am working on the CNTK wrapper right now :)

The x64 version was linked to the CNTK Dlls, so I changed a bit the wrapper and loaded it explicitly only if needed (the wrapper dll is implicitly linked to CNTK libraries).

I also refactored the wrapper interface a bit to simplify algorithm programming. DQN and Double-DQN seem to be working with the mountain car and the pole balancing task, and are trying to understand DDPG and AC3 to try to make them work with all the CNTK stuff inside the wrapper. (branch is named "merging-rolands-branch")

After that (one week hopefuly), my plan is to update CNTK and try to make it work on GPUs. Distributed learning via CNTK sounds more difficult to accomplish, but it's definitely caught my atention, yeah

Any help is welcome if you are bored ;)
If you want

**Comment by borjafdezgauna** [comment]
CNTK library updated to version 2.5.1. RLSimion can now run on either a multi-core CPU or a GPU (using "-gpu" flag). By default, CPU is used from Badger because in all the tests I did so far, the multi-threaded CPU version outperforms the GPU version. This is most probably because we do a lot of CPU stuff and GPU-CPU data transfers are expensive. It's worth trying to optimize the implementation to make better use of the GPU
I will put a pin on the distributed implementation of CNTK but it is not a priority right now, since the most important factor is in my case the number of experiments rather than the experiments themselves
